#
# Copyright (C) 2023 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

## Kernel
TARGET_KERNEL_VARIANT_CONFIG := aml_tab_variant_defconfig

include device/bananapi/m5/BoardConfig.mk

BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE := 250000000  # ~238 MiB
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE := 50000000  # ~50 MiB
BOARD_VENDOR_DLKMIMAGE_PARTITION_RESERVED_SIZE := 8388608  # 8 MiB